# Generated by Django 4.0.5 on 2022-09-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='опубликовано'),
        ),
    ]
